[package]
name = "vulkan"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.27.2"
vulkanite_vulkan = { path = "../../crates/vulkanite_vulkan", version = "0.1" }

tracing = "0.1.34"
tracing-subscriber = "0.3.1"